### ISSUE TITLE
Unable to get logs into Azure Logs / Application Insights

### ISSUE THREAD

**Issue by MikePennington** [tntwist/NL.Serverless.AspNetCore#19]
I'm still struggling getting logs to show up in Azure. When I run using the `func` cli locally I get logs in the console, but not when I deploy to Azure. Here's what I'm seeing:

In the below example I am testing logging using both the ILogger injected via Azure and the one I'm injecting using C#:
```
        private readonly ILogger<WebAppProxyFunction> _logger;

        public WebAppProxyFunction(IFunctionsRequestHandler requestHandler, ILogger<WebAppProxyFunction> logger) : base(requestHandler)
        {
            _logger = logger;
        }

        [FunctionName("webapi")]
        public async Task<IActionResult> Run(
           [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", "put", "patch", "delete", "options", Route = "{*any}")] HttpRequest req,
           ILogger log)
        {
            log.LogError("1a");
            log.LogInformation("2a");

            _logger.LogError("1b");
            _logger.LogInformation("2b");
            return await ProcessRequestAsync(req, log);
        }
```
In this case _both_ loggers are logging correctly, and I see `1a 2a 1b 2b` all in the logs in Azure.

However, when I try to inject ILogger into a controller in the webapi I'm still not getting anything in Azure. I've tried messing around with both the Startup.cs and Program.cs, but to no avail so far.

```
    [ApiController]
    [Route("api/health")]
    public class HealthController : ControllerBase
    {
        private readonly ILogger<HealthController> _logger;

        public HealthController(ILogger<HealthController> logger)
        {
            _logger = logger;
        }

        [HttpGet("")]
        public string Health()
        {
            _logger.LogTrace("TRACE");
            _logger.LogDebug("DEBUG");
            _logger.LogInformation("INFO");
            _logger.LogError("ERROR");
            _logger.LogCritical("CRITICAL");
            return "Hello, is it me you're looking for?";
        }
    }
```

The above class doesn't log anything into Azure when triggered.

Any help would be greatly appreciated!

**Comment by tntwist** [comment]
Hi,

ApplicationInsights should just work like in the [docs ](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core) from Microsoft stated.

But unfortunately when registering ApplicationInsights in the Startup of the web app, the deprecated Microsoft.AspNetCore.Hosting.IHostingEnvironment was not registered in the application services.

I fixed this by adding the required Interface to the FunctionWebHostEnvironment and adding it as Service for the Interface.

With this I was able to see the logs of the web app in Azure:
![image](https://user-images.githubusercontent.com/6589385/84085458-eef72280-a9e5-11ea-9f11-83fc09c10718.png)

You can see that there are some exceptions on the bottom. They are related to an open issue of ApplicationInsights: #https://github.com/microsoft/ApplicationInsights-dotnet/issues/973
But since we still get the logs it should not be a big issue.

**Comment by MikePennington** [comment]
Hello, I am sorry, but I don't quite follow what you are saying here. And to be clear, Application Insights metrics work just fine, it's just the logs that aren't showing in Azure.

To test to make sure it wasn't doing anything wrong on my end, I tested adding a logging statement in `NL.Serverless.AspNetCore.WebApp/Controllers/ValuesController.cs` in this repo.

```
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            _logger.LogError("ERROR");
            return new string[] { "value1", "value2" };
        }
```
This log message shows up fine when I run `func start` locally, but does not show in the Console in Azure. Where you saying that the fix is something I need to add to my app or something you are able to add to NL.Serverless.AspNetCore?

**Comment by tntwist** [comment]
Hi,
maybe I didn´t understood your issue quite right. What console in azure do you use for the logs? Could you send me a screenshot or a short instruction how you open it. I´m using the Log stream for viewing the logs of the function app:

![image](https://user-images.githubusercontent.com/6589385/84141668-d4f42900-aa53-11ea-9d6a-5e130474488d.png)

The fix was related to the startup code inside the library code:
https://github.com/tntwist/NL.Serverless.AspNetCore/commit/ec3630dbe36eed877cc8168f28d441d9d4e1cdc9

**Comment by MikePennington** [comment]
@tntwist yes I am looking at the Log Stream also.

I checked out the the `dev` branch where you made that recent commit and deployed it to Azure using `func azure functionapp publish mike-sample`. See below:

![log-stream](https://user-images.githubusercontent.com/750344/84188364-1935f800-aa59-11ea-90bb-a8d3d0151cd5.png)

1. I'm getting messages in the logs now! Yeah!
1. I don't seem to be able to get anything except for Critical and Error level. I tried changing the log level in `host.json` in the FunctionApp, and also tried changing the log level in `appsettings.json` in the WebApp, but neither seemed to work. Do you know how I can increase the log level?

Thank you so much! I'm looking forward to getting these changes published in the next version.

**Comment by tntwist** [comment]
@MikePennington great that its working with the fix in the dev branch. 🎉 

> I don't seem to be able to get anything except for Critical and Error level. I tried changing the log level in host.json in the FunctionApp, and also tried changing the log level in appsettings.json in the WebApp, but neither seemed to work. Do you know how I can increase the log level?

I found out that ApplicationInsights have their own LogLevels [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#control-logging-level)

So I added (https://github.com/tntwist/NL.Serverless.AspNetCore/commit/a6f34847c9410e773753fcca0ed2c2f208b89278) these log levels to the `appsettings.json` of the NL.Serverless.AspNetCore.WebApp and it worked 😄 

![image](https://user-images.githubusercontent.com/6589385/84206343-3e555580-aaaf-11ea-86c3-a7b2750f0261.png)
I marked the entry for the "INFO" log green, it will appear in blue in the console.

> Thank you so much! I'm looking forward to getting these changes published in the next version.
Thanks! 😃 I hope that I can bundle the next version tomorrow.

Please don´t forget to add these lines to the web app of your real application afterwards: https://github.com/tntwist/NL.Serverless.AspNetCore/blob/a6f34847c9410e773753fcca0ed2c2f208b89278/src/NL.Serverless.AspNetCore.WebApp/Startup.cs#L24

https://github.com/tntwist/NL.Serverless.AspNetCore/blob/a6f34847c9410e773753fcca0ed2c2f208b89278/src/NL.Serverless.AspNetCore.WebApp/NL.Serverless.AspNetCore.WebApp.csproj#L10

**Comment by tntwist** [comment]
Hi,
the new version 3.0.7.2 is now released. It can take up to 1 hour for nuget.org to index the new version.

Greetings
